alipayconfigs:
  gateway: https://mapi.alipay.com/gateway.do
  subject: "全能商城qnnshop.com订单:{{id}}"
  return_url: "http://www.qnnshop.com/orders/{{id}}/success"
  show_url: "http://www.qnnshop.com/orders/{{id}}"
  successful_payment:
    success: 交易成功，我们会在48小时内发货。
    options:
      positionClass: "toast-top-full-width"
      timeOut: 180000 # 时间，毫秒
  failed_payment:
    error: 支付过程出现错误，如有问题请咨询客服。
    options:
      positionClass: "toast-top-full-width"
      timeOut: 180000 # 时间，毫秒

# __init__ 是默认，不同状态的各设置会覆盖 __init__ 直接下属对应的属性。
successfully_creating_order:
  __init__:
    success: 成功创建订单。
    options:
      positionClass: "toast-top-full-width" # 样式，位于页顶
      timeOut: 180000 # 时间，毫秒
  等待买家付款:
    success: 成功创建订单。请为您的订单付款。
  等待卖家发货:
    success: 成功创建订单。我们会在48小时内发货。

# 默认的订单状态
statuses:
  - 等待买家付款
  - 等待卖家发货
  - 卖家已发货，等待买家收货
  - 买家已取消
  - 卖家已取消
  - 交易成功

# 当订单状态是如下任一状态时，改订单可被用户取消
cancelable_statuses:
  - 等待买家付款
  - 等待卖家发货

payable_statuses:
  - 等待买家付款

# 取消订单的原因
reasons_to_cancel:
  - 资料填写错误
  - 发现现在不需要购买
  - 已去别的地方购买

# 选择货到付款的初始订单状态
cod_initial_status: 等待卖家发货

# 选择其他支付方式的初始订单状态
payment_initial_status: 等待买家付款

alipay: 支付宝

status_if_user_paid: 等待卖家发货

# 买家取消订单后，订单的状态
buyer_cancel_status: 买家已取消

# 管理员所有订单页默认不显示下列状态的订单
default_statuses_not_to_show:
  - 买家已取消
  - 卖家已取消
  - 交易成功

# 启用发票功能
invoice_enabled: true

# 预设的快递公司
express_companies:
  顺丰: http://sf-express.com/
  韵达: http://www.yundaex.com/
  圆通: http://www.yto.net.cn/
  申通: http://www.sto.cn/
  EMS: http://www.ems.com.cn/

# 管理员账户
admins:
  - username: caiguanhao
    password: $2a$10$RGioxd1LvP0oCZJXSEakpuSsv95kRIRaDoJKnNJ9H9sK4tfpNFpeC
