safe:
  jd-3340:
    name: jd-3340

    title: jd-3340
    subtitle: jd-3340

    original_price: 1498
    price: 498

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 30cm以下
      锁具: 单独密码开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: http://shop.qnnimg.com/products/jd-3340-01.jpg
	
    slides:
      - http://shop.qnnimg.com/products/jd-3340-01.jpg
      - http://shop.qnnimg.com/products/jd-3340-02.jpg
      - http://shop.qnnimg.com/products/jd-3340-03.jpg
      - http://shop.qnnimg.com/products/jd-3340-04.jpg

    recommendations:
      - /safe/hg-3342

    body: |
      <img src="http://shop.qnnimg.com/products/jd-3340-gs.jpg">

  ia-53:
    name: ia-53

    title: ia-53
    subtitle: ia-53

    original_price: 1745
    price: 698

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 30cm以下
      锁具: 单独密码开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: http://shop.qnnimg.com/products/ia-53-01.jpg
	
    slides:
      - http://shop.qnnimg.com/products/ia-53-01.jpg
      - http://shop.qnnimg.com/products/ia-53-02.jpg
      - http://shop.qnnimg.com/products/ia-53-03.jpg
      - http://shop.qnnimg.com/products/ia-53-04.jpg

    recommendations:
      - /safe/hg-3342

    body: |
      <img src="http://shop.qnnimg.com/products/ia-53-gs.jpg">
