safe:
  jd-3340:
    name: jd-3340

    title: jd-3340
    subtitle: jd-3340

    original_price: 1498
    price: 498

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 30cm以下
      锁具: 单独密码开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    slides:
      - http://stores.qnnimg.com/products/hg-2740-01.jpg
      - http://stores.qnnimg.com/products/hg-3342-01.jpg
      - http://stores.qnnimg.com/products/hg-2740-01.jpg

    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/hg-3342

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  hg-3342:
    name: 新皇冠HG-3342

    title: 保险柜十大品牌全能新皇冠HG-3342
    subtitle: 保险柜十大品牌

    price: 2010

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 30cm以下
      锁具: 密码+钥匙开启、单独指纹开启、指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 42.2公斤

    image: http://stores.qnnimg.com/products-small/hg-3342.jpg

    slides:
      - http://stores.qnnimg.com/products/hg-3342-01.jpg
      - http://stores.qnnimg.com/products/hg-2740-01.jpg

    body: |
      <img alt="保险柜十大品牌HG-3342功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  ai-5842:
    name: AI-5842

    title: AI-5842
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 31-50cm
      锁具: 单独指纹开启、指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/ai-5842.jpg

    slides:
      - /images/safe/ai-5842.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/iv-3342

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  ai-3340:
    name: AI-3340

    title: AI-3340
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 51-80cm
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/ai-3340.jpg

    slides:
      - /images/safe/ai-3340.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/ai-3340

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  lg-2535:
    name: LG-2535

    title: LG-2535
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 81cm以上
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/lg-2535.jpg

    slides:
      - /images/safe/lg-2535.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/lg-2535

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  cx-1625:
    name: CX-1625

    title: CX-1625
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 81cm以上
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/cx-1625.jpg

    slides:
      - /images/safe/cx-1625.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/cx-1625

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  jd-7645:
    name: JD-7645

    title: JD-5842
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 81cm以上
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/jd-7645.jpg

    slides:
      - /images/safe/jd-7645.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/jd-7645

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  iv-3342:
    name: IV-3342

    title: IV-3342
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 81cm以上
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/iv-3342.jpg

    slides:
      - /images/safe/iv-3342.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/iv-3342

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  cki-253530:
    name: CKI-253530

    title: CKI-253530
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 81cm以上
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/cki-253530.jpg

    slides:
      - /images/safe/cki-253530.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/cki-253530

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">

  cx-2046:
    name: CX-2046

    title: CX-2046
    subtitle: 保险柜十大品牌

    original_price: 1300
    price: 998

    filter:
      使用范围: 家居使用、企业使用、酒店使用
      类别: 保管箱、3C认证保险柜、办公文件柜、配件
      高度: 81cm以上
      锁具: 指纹+钥匙开启

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    image: /images/safe/cx-2046.jpg

    slides:
      - /images/safe/cx-2046.jpg


    side_html: |
      <img style="border: 1px solid #CCC;" src="http://stores.qnnimg.com/products-small/hg-2740.jpg" width="330" height="330">

    recommendations:
      - /safe/cx-2046

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">
