新皇冠:
  HG-2740:
    name: 新皇冠HG-2740

    title: 保险柜十大品牌全能新皇冠HG-2740
    subtitle: 保险柜十大品牌

    price: 1846
    promo_price: 1799

    size: (高)290x(宽)450x(深)270mm
    thickness: 门10mm，箱4-6mm
    weight: 33.8公斤

    images:
      - http://stores.qnnimg.com/products-small/hg-2740.jpg

    slides:
      - http://stores.qnnimg.com/products/hg-2740-01.jpg
      - http://stores.qnnimg.com/products/hg-3342-01.jpg
      - http://stores.qnnimg.com/products/hg-2740-01.jpg

    body: |
      <img alt="保险柜十大品牌HG-2740功能特征" height="1142" src="http://stores.qnnimg.com/products/hg-gn.jpg" width="538">
